name: wassup_front
description: "ayo wassupðŸ¥³ðŸ«µðŸ¼"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  video_player: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/avatar.jpg
